### ISSUE TITLE
[Bug] Upgrading mysqld-cdc to 2.4.1 caused Flink WEB UI metrics to keep spinning (yarn on per mode). The same configuration did not have this issue in mysqld-cdc 2.3.0.

### ISSUE THREAD

**Issue by jiaominmin** [apache/flink-cdc#2483] opened 2023-09-12 08:20 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.13.6

### Flink CDC version

2.4.1

### Database and its version

mysql 8

### Minimal reproduce step

升级mysl-cdc到2.4.1，导致flink web ui 各项指标一直转圈（yarn on per模式），相同的配置在mysl-cdc 2.3.0中不会出现该问题

Upgrading mysqld-cdc to 2.4.1 caused Flink web UI metrics to keep spinning (yarn on per mode). The same configuration did not have this issue in mysqld-cdc 2.3.0.

### What did you expect to see?

我不知道原因是什么，如何去解决

### What did you see instead?

flink web ui 各项指标一直转圈

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

-这个是代码，如果不将信息sink到kafka则不会出现上述情况

  //使用CDC Source从MySQL读取数据
                DataStream<OperationData> mysqlSource = env.fromSource(mysqlSourceBuilder.build(), WatermarkStrategy.noWatermarks(), "Mysql  Source")
                    .uid("source").name("Mysql Source");

                DataStream<String> test = mysqlSource.map(line -> {
                    return String.valueOf(line.getTable());
                });

                FlinkKafkaProducer<String> odsKafkaProducer = new FlinkKafkaProducer<>(
                    “topicId”, new SimpleStringSchema(), propertiesKafka);
                test.addSink(odsKafkaProducer).uid("sink").name("ODS Kafka Sink");;

**Comment by jiaominmin** [comment] 2023-09-19 02:52
//使用CDC Source从MySQL读取数据
                DataStream<OperationData> mysqlSource = env.fromSource(mysqlSourceBuilder.build(), WatermarkStrategy.noWatermarks(), "Mysql  Source")
                    .uid("source").name("Mysql Source");

                DataStream<String> test = mysqlSource.map(line -> {
                    return String.valueOf(line.getTable());
                });

                FlinkKafkaProducer<String> odsKafkaProducer = new FlinkKafkaProducer<>(
                    config.concatNamespace(KAFKA_TOPIC_SEPARATOR, ProcessedData.KAFKA_TOPIC_ODS), new SimpleStringSchema(), propertiesKafka);
                test.addSink(odsKafkaProducer).uid("sink").name("ODS Kafka Sink");

**Comment by qy8502** [comment] 2023-10-08 02:41
> ```
>             FlinkKafkaProducer<String> odsKafkaProducer = new FlinkKafkaProducer<>(
>                 config.concatNamespace(KAFKA_TOPIC_SEPARATOR, ProcessedData.KAFKA_TOPIC_ODS), new SimpleStringSchema(), propertiesKafka);
>             test.addSink(odsKafkaProducer).uid("sink").name("ODS Kafka Sink");
> ```
I have the same problem. 
Get the metrics is the time interval must be through MetricFetcherImpl# queryMetrics method sends the request akka: / / flink - metrics/user/RPC/MetricQueryService. This RPC asynchronous request gets a failure result in the case of a problem. Print the failure found the reason for the error NoSuchMethodError: org.apache.kafka.com mon. Metric. A value ().
```
java.util.concurrent.ExecutionException: Boxed Error
    at scala.concurrent.impl.Promise$.resolver(Promise.scala:59)
    at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:51)
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
    at akka.pattern.PromiseActorRef.$bang(AskSupport.scala:572)
    at akka.actor.ActorRef.tell(ActorRef.scala:126)
    at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleCallAsync(AkkaRpcActor.java:423)
    at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:210)
    at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:158)
    at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
    at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
    at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
    at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
    at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
    at akka.actor.ActorCell.invoke(ActorCell.scala:561)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
    at akka.dispatch.Mailbox.run(Mailbox.scala:225)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.apache.kafka.common.Metric.value()D
    at org.apache.flink.streaming.connectors.kafka.internals.metrics.KafkaMetricMutableWrapper.getValue(KafkaMetricMutableWrapper.java:37)
    at org.apache.flink.streaming.connectors.kafka.internals.metrics.KafkaMetricMutableWrapper.getValue(KafkaMetricMutableWrapper.java:27)
    at org.apache.flink.runtime.metrics.dump.MetricDumpSerialization.serializeGauge(MetricDumpSerialization.java:267)
    at org.apache.flink.runtime.metrics.dump.MetricDumpSerialization.access$200(MetricDumpSerialization.java:51)
    at org.apache.flink.runtime.metrics.dump.MetricDumpSerialization$MetricDumpSerializer.serialize(MetricDumpSerialization.java:167)
    at org.apache.flink.runtime.metrics.dump.MetricQueryService.lambda$queryMetrics$2(MetricQueryService.java:131)
    at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleCallAsync(AkkaRpcActor.java:419)
    ... 18 more
Caused by: java.lang.NoSuchMethodError: org.apache.kafka.common.Metric.value()D
```
That's obviously a problem caused by dependency conflict. Query org.apache.kafka.com mon. Metric class in package, and through the gradle query dependencies, determine the org. Apache. Kafka: kafka - there was a conflict, clients 3.2.0 version of the Metric value method.
```
\--- com.ververica:flink-connector-mysql-cdc:2.4.1
     +--- com.ververica:flink-connector-debezium:2.4.1
     |    +--- io.debezium:debezium-embedded:1.9.7.Final
     |    |    +--- org.apache.kafka:connect-api:3.2.0
     |    |    |    +--- javax.ws.rs:javax.ws.rs-api:2.1.1
     |    |    |    \--- org.apache.kafka:kafka-clients:3.2.0 (*)
 
+--- org.apache.flink:flink-connector-kafka_2.11:1.13.6
|    +--- org.apache.kafka:kafka-clients:2.4.1 -> 3.2.0
```
The problem is resolved by removing the problem dependency in cdc2.4.1.
```
flinkShadowJar('com.ververica:flink-connector-mysql-cdc:2.4.1') {
    exclude group: 'org.apache.kafka', module: 'kafka-clients'
}
```

**Comment by PatrickRen** [comment] 2024-03-20 08:03
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-03-20 08:03 UTC
Labels: bug
