### ISSUE TITLE
[Bug] java.lang.NoClassDefFoundError: Could not initialize class org.apache.kafka.connect.json.JsonConverterConfig

### ISSUE THREAD

**Issue by ccc66666** [apache/flink-cdc#2491] opened 2023-09-14 03:14 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.14.0

### Flink CDC version

2.3.0

### Database and its version

MySQL5.7

### Minimal reproduce step

 //设置相关ck的参数
        env.enableCheckpointing(360000L);
        env.getCheckpointConfig().setMaxConcurrentCheckpoints(1);
        env.getCheckpointConfig().setCheckpointTimeout(360000L);
        env.getCheckpointConfig().setFailOnCheckpointingErrors(false);
        env.getCheckpointConfig().setCheckpointingMode(CheckpointingMode.EXACTLY_ONCE);
        env.getCheckpointConfig().enableExternalizedCheckpoints(CheckpointConfig.ExternalizedCheckpointCleanup.RETAIN_ON_CANCELLATION);

        //cdc的相关参数
        Properties prop = new Properties();
        prop.setProperty("snapshot.locking.mode","none");

        //使用cdc来读取binlog日志
        DebeziumSourceFunction<String> dataSource = MySqlSource.<String>builder()
                .hostname("")
                .port(3306)
                .username("rp")
                .password("u5")
                .databaseList("iap")
                .tableList("iap.cdc_test_1")
                .deserializer(new JsonDebeziumDeserializationSchema())
                .startupOptions(StartupOptions.latest())
                .debeziumProperties(prop)
                .build();

        SingleOutputStreamOperator<String> streamSource = env.addSource(dataSource).name("data-source");
        streamSource.print("======>"+streamSource);
but it causes an error:
 java.lang.NoClassDefFoundError: Could not initialize class org.apache.kafka.connect.json.JsonConverterConfig

### What did you expect to see?

run success

### What did you see instead?

success

### Anything else?

no

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by mayaming** [comment] 2023-11-23 06:51
I encounter the same problem and the reason is the version of my flink kafka connector is too low.

It's NOT a problem that JsonConverterConfig is not found. In my case the class could be found but fails in static block initialization:

`        CONFIG.define(
            DECIMAL_FORMAT_CONFIG, Type.STRING, DECIMAL_FORMAT_DEFAULT,
            ConfigDef.CaseInsensitiveValidString.in(
                DecimalFormat.BASE64.name(),
                DecimalFormat.NUMERIC.name()),
            Importance.LOW, DECIMAL_FORMAT_DOC, group, orderInGroup++,
            Width.MEDIUM, DECIMAL_FORMAT_DISPLAY);
`
Here ConfigDef is defined in org.apache.kafka:kafka-clients, and CaseInsensitiveValidString is not available if your version is too low for some reason. I upgrade my kafka connector the problem is gone.

You could check your JsonConverterConfig code if there's any problem in its static block initialization. Hope it helps.

**Comment by PatrickRen** [comment] 2024-04-09 06:00
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).

**Closed by PatrickRen** 2024-04-09 06:00 UTC
Labels: bug
